### ISSUE TITLE
Plugin not working - Missing included js files

### ISSUE THREAD

**Issue by pkarecki** [LotusBreath/OneStepCheckout#1]
After installation of current version from github AJAX requests are not working at all. 
Probably POST URL-s are not set in object options. 

I have tried also version available to download from website store.lotusbreath.com after submitting an order. This version seams very outdated and does not generate even menu in admin panel.

Please upload version working on https://store.lotusbreath.com/onestepcheckout/ for example to different branch so i could move the fixes to current master.

**Comment by J-dsgn** [comment]
Is this issue already solved in current download?

**Comment by trunglv** [comment]
Hi , 
Pls check a new commit https://github.com/LotusBreath/OneStepCheckout/commit/ad4c32471b51a9242dd18f28b9a1bfbff8324152
